name: Build helm chart

on:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
      - '[0-9]+.x'
    paths:
      - 'helm/**'

jobs:
  helm:
    uses: onecx/ci-product/.github/workflows/build.yml@v1
    secrets: inherit

